---
- name: "Install mysql server"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - mariadb
      - mariadb-server
- name: "mysql pyton"
  yum:
    name: MySQL-python
    state: present
- service:
    name: mariadb
    state: started
- name: "Create database"
  mysql_db:
    name: "{{database_name}}"
    state: present